// Counter
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

//UserList
export const LOAD_USERS = 'LOAD_USERS'

//ToDoList
export const SELECT_FILTER = 'SELECT_FILTER'
export const ADD_ITEM = 'ADD_ITEM'
export const CHECK_UNCHECK_ITEM = 'CHECK_UNCHECK_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'